[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "crashball"
# The game's title. This will show up in the tile bar of your executable.
title = "Crashball"
version = "0.4.2"
authors = ["mooff", "kota"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "2.19"
edition = "standard"

[dependencies]
maw = "1.3.2"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "crashball"
# Your username on Itch.io.
username = "moofee"
